# Generated by Django 3.0.8 on 2020-08-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameid',
            old_name='gameid',
            new_name='gid',
        ),
        migrations.RenameField(
            model_name='gameid',
            old_name='player1',
            new_name='players',
        ),
        migrations.RemoveField(
            model_name='gameid',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='gameid',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='gameid',
            name='player4',
        ),
    ]
