# Generated by Django 3.0.8 on 2020-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200807_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameid',
            name='counting',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
