# Generated by Django 3.0.8 on 2020-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_gameid_counting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameid',
            name='counting',
            field=models.TextField(),
        ),
    ]
