# Generated by Django 3.0.8 on 2020-08-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200808_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameid',
            name='decks',
            field=models.TextField(null=True),
        ),
    ]
