# Generated by Django 3.0.8 on 2020-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_gameid_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameid',
            name='chance',
            field=models.IntegerField(null=True),
        ),
    ]
