# Generated by Django 3.0.8 on 2020-08-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_gameid_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameid',
            name='deck1',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameid',
            name='deck2',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameid',
            name='deck3',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameid',
            name='deck4',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameid',
            name='played',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
