# Generated by Django 3.0.8 on 2020-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_gameid_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameid',
            name='passing',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
