# Generated by Django 3.0.8 on 2020-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_gameid_passing'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameid',
            name='by',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameid',
            name='by2',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameid',
            name='typ',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
