# Generated by Django 3.0.8 on 2020-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200824_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameid',
            name='by',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='by2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='chance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='deck1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='deck2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='deck3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='deck4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='decks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='passing',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='played',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='stock',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='typ',
            field=models.IntegerField(null=True),
        ),
    ]
