# Generated by Django 3.0.8 on 2020-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200824_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameid',
            name='played',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
