# Generated by Django 3.0.8 on 2020-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20200824_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameid',
            name='deck1',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='deck2',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='deck3',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='gameid',
            name='deck4',
            field=models.IntegerField(default=13),
        ),
    ]
