# Generated by Django 3.0.8 on 2020-09-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20200908_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameid',
            name='typ',
            field=models.IntegerField(default=0),
        ),
    ]
