# Generated by Django 3.0.8 on 2020-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20200908_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameid',
            name='chance',
            field=models.TextField(null=True),
        ),
    ]
